INSERT INTO USERS (NAME, USERNAME, PASSWORD) VALUES('Pedro', 'pedroalencar', '123')
INSERT INTO USERS (NAME, USERNAME, PASSWORD) VALUES('Lucas', 'lucasalencar', '123')
INSERT INTO USERS (NAME, USERNAME, PASSWORD) VALUES('Joao', 'joaodasilva', '123')

INSERT INTO ROLES(ID, NAME) VALUES (1, 'TUTOR')
INSERT INTO ROLES(ID, NAME) VALUES (2, 'ADOTANTE')


INSERT INTO PETS(ID, NAME, IS_ADOPTED, USER_ID)VALUES(1, 'Manda Chuva', FALSE, 2)
INSERT INTO PETS(ID, NAME, IS_ADOPTED, USER_ID)VALUES(2, 'Mandy', FALSE, 2)

INSERT INTO USERS_ROLES(USER_ENTITY_ID, ROLES_ID)VALUES(1,2)
INSERT INTO USERS_ROLES(USER_ENTITY_ID, ROLES_ID)VALUES(2,1)
INSERT INTO USERS_ROLES(USER_ENTITY_ID, ROLES_ID)VALUES(2,2)
